spring.application.name=AuthenticationService
server.port=9093

jwt.secret=wN3p9X2y8G6vR4tZ1bJ5kM7sH0qL8dF3vP2cX9aY6wS1eN0uR7mB4jK5oV8xT2pL9mN4qR7sU5vX8yZ2
jwt.expiration=259200000
spring.messages.basename=messages
spring.messages.encoding=UTF-8

spring.datasource.url=jdbc:mysql://localhost:3306/erp_db
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect


logging.level.org.springframework.secrurity=DEBUG
logging.level.com.example.auth=DEBUG

#server.servlet.context-path=/auth-service